try {
    eval("-");
} catch (EvalError) {
  new EvalError(["se a producido error",[ejercicio13.js,[100]]])   
}